CREATE DATABASE NEW_PERU_BANK;

USE NEW_PERU_BANK;

CREATE TABLE `usuarios` (
  `DNI_USU` varchar(8) NOT NULL,
  `NOM_USU` varchar(50) NOT NULL,
  `PASS_USU` blob NOT NULL,
  PRIMARY KEY (`DNI_USU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cuentas` (
  `ID_CUENTAS` int(11) NOT NULL AUTO_INCREMENT,
  `NUM_CUENTA` varchar(16) NOT NULL,
  `MONEDA` varchar(15) NOT NULL,
  `MONTO` float(5,2) NOT NULL,
  `FK_CUENTAS_USUARIO` varchar(8) NOT NULL,
  PRIMARY KEY (`ID_CUENTAS`),
  KEY `FK_CUENTAS_USUARIO` (`FK_CUENTAS_USUARIO`),
  CONSTRAINT `cuentas_ibfk_1` FOREIGN KEY (`FK_CUENTAS_USUARIO`) REFERENCES `usuarios` (`DNI_USU`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `transacciones` (
  `ID_TRANSAC` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO` varchar(15) NOT NULL,
  `FK_TRANSAC_CUENTAS` int(11) NOT NULL,
  PRIMARY KEY (`ID_TRANSAC`),
  KEY `FK_TRANSAC_CUENTAS` (`FK_TRANSAC_CUENTAS`),
  CONSTRAINT `transacciones_ibfk_1` FOREIGN KEY (`FK_TRANSAC_CUENTAS`) REFERENCES `cuentas` (`ID_CUENTAS`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;